"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
from collections import defaultdict
from functools import reduce


def highly_divisible_triangular_num(n_div) -> int:
    num = 0
    ans = 0
    k = 1
    while True:
        num += k
        tmp = num
        i = 2
        divs = defaultdict(int)
        while tmp > 1:
            while tmp % i == 0:
                tmp //= i
                divs[i] += 1
            i += 1
        if divs:
            ans = reduce(lambda a, b: a * b, [v + 1 for v in divs.values()])
            # Why different value is returned????
            # ans = reduce(lambda a, b: (a+1) * (b+1), divs.values())
        if ans < n_div:
            k += 1
        else:
            print(num, k, ans)
            break
    print(divs, divs.values(), reduce(lambda a, b: a * b, [v + 1 for v in divs.values()]))
    r = 1
    for v in divs.values():
        r *= (v + 1)
    print(r)
    return num


if __name__ == '__main__':
    print(highly_divisible_triangular_num(5))  # 28
    print(highly_divisible_triangular_num(500))
